### ISSUE TITLE
pops.js is blocked by adblock

### ISSUE THREAD

**Issue by pyalot** [gabxgz/pops.js#1]
If you have a .net domain and place the pops.js file in the root folder it's blocked by virtually every adblocking plugin because of this list: https://easylist-downloads.adblockplus.org/easylist.txt

**Comment by gabxgz** [comment]
I haven't looked at this plugin in a while. In retrospect it probably should be blocked by every adblock plugin. Please feel free to rename your local copy of the folder to something that won't be blocked by adblock.
